#+AUTHOR: Karim Aziiev
#+EMAIL: karim.aziiev@gmail.com
#+OPTIONS: ^:nil tags:nil num:nil

* About
The simple application allows users to manage their todo lists. They can
create, read, update, and delete todo items.

* Todo-App                                                   :TOC_3_gh:QUOTE:
#+BEGIN_QUOTE
- [[#about][About]]
  - [[#installation][Installation]]
  - [[#environment][Environment]]
  - [[#running-the-application][Running the Application]]
  - [[#api][API]]
    - [[#get-todos][GET =/todos=]]
    - [[#post-add-todo][POST =/add-todo=]]
    - [[#put-edit-todoid][PUT =/edit-todo/:id=]]
    - [[#delete-delete-todoid][DELETE =/delete-todo/:id=]]
#+END_QUOTE

** Installation

First, clone the repository:

#+BEGIN_EXAMPLE
  git clone https://github.com/KarimAziev/nodejs-todo-app.git
#+END_EXAMPLE

Then, navigate into the directory:

#+BEGIN_EXAMPLE
  cd nodejs-todo-app
#+END_EXAMPLE

** Environment

Create the file =nodemon.json= file:

#+BEGIN_EXAMPLE
cp ./nodemon.example.json ./nodemon.json
#+END_EXAMPLE

Edit this file with your actual environment variables based on the connection uri:

#+begin_src typescript
  const uri: string = `mongodb+srv://${process.env.MONGO_USER}:${process.env.MONGO_PASSWORD}@${process.env.MONGO_HOST}/${process.env.MONGO_DB}?retryWrites=true&w=majority`;
#+end_src

- =PORT=: The port the server will listen on. Default is 4000.
- =MONGO_USER=: Your MongoDB username.
- =MONGO_PASSWORD=: Your MongoDB password.
- =MONGO_DB=: Your MongoDB database name.
- =MONGO_HOST=: Your MongoDB host.



** Running the Application

After setting up the environment variables run:

#+BEGIN_EXAMPLE
npm install && npm start
#+END_EXAMPLE

The server should now be running at =http://localhost:4000=.



** API

*** GET =/todos=

Get all todos.

*Example*:

#+BEGIN_SRC restclient
GET http://localhost:4000/todos
#+END_SRC

*Response*:

#+begin_example
{
    "todos": [
        {
            "_id": "64d909d4c7e2fb853d952876",
            "name": "Create app",
            "description": "Create simple todo app",
            "status": false,
            "createdAt": "2023-08-13T16:50:28.242Z",
            "updatedAt": "2023-08-13T16:50:28.242Z",
            "__v": 0
        },
    ]
}
#+end_example


*** POST =/add-todo=

Add a new todo (Fields: =name=, =description=, =status=)

*Example*:

#+begin_src restclient :wrap example
POST http://localhost:4000/add-todo
Content-Type: application/json
{"name": "Task 2", "description": "My task 2", "status": false}
#+end_src

*Response*:


#+begin_example
{
  "message": "Todo added",
  "todos": [
    {
      "_id": "64d909d4c7e2fb853d952876",
      "name": "Create app",
      "description": "Create simple todo app",
      "status": false,
      "createdAt": "2023-08-13T16:50:28.242Z",
      "updatedAt": "2023-08-13T16:50:28.242Z",
      "__v": 0
    },
    {
      "_id": "64d90a28c7e2fb853d952879",
      "name": "Task 2",
      "description": "My task 2",
      "status": false,
      "createdAt": "2023-08-13T16:51:52.543Z",
      "updatedAt": "2023-08-13T16:51:52.543Z",
      "__v": 0
    }
  ]
}
#+end_example



*** PUT =/edit-todo/:id=

Edit a todo (Fields: =name=, =description=, =status=)

*Example*:

#+begin_src restclient 
PUT http://localhost:4000/edit-todo/64d909d4c7e2fb853d952876
Content-Type: application/json

{"name": "Create app", "description": "Create simple todo app", "status": true}
#+end_src

*Response*:
#+begin_example
{
  "message": "Todo updated",
  "todos": [
    {
      "_id": "64d909d4c7e2fb853d952876",
      "name": "Create app",
      "description": "Create simple todo app",
      "status": true,
      "createdAt": "2023-08-13T16:50:28.242Z",
      "updatedAt": "2023-08-13T16:52:55.194Z",
      "__v": 0
    },
    {
      "_id": "64d90a28c7e2fb853d952879",
      "name": "Task 2",
      "description": "My task 2",
      "status": false,
      "createdAt": "2023-08-13T16:51:52.543Z",
      "updatedAt": "2023-08-13T16:51:52.543Z",
      "__v": 0
    }
  ]
}

#+end_example


*** DELETE =/delete-todo/:id=

Delete a todo.

*Example*:

#+begin_src restclient
DELETE http://localhost:4000/delete-todo/64d909d4c7e2fb853d952876
#+end_src

*Response*:
#+begin_example
{
  "message": "Todo deleted",
  "todos": [
    {
      "_id": "64d90a28c7e2fb853d952879",
      "name": "Task 2",
      "description": "My task 2",
      "status": false,
      "createdAt": "2023-08-13T16:51:52.543Z",
      "updatedAt": "2023-08-13T16:51:52.543Z",
      "__v": 0
    }
  ]
}

#+end_example
